version: '2'
services:
    tastfondation-app:
        image: tastfondation
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://tastfondation-postgresql:5432/TastFondation
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    tastfondation-postgresql:
        extends:
            file: postgresql.yml
            service: tastfondation-postgresql
